USE gorefill;
SELECT 
    COLUMN_NAME, 
    COLUMN_TYPE, 
    IS_NULLABLE, 
    COLUMN_DEFAULT,
    COLUMN_COMMENT
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = 'gorefill' 
AND TABLE_NAME = 'orders'
ORDER BY ORDINAL_POSITION;
